spring.application.name=todoist_api
spring.datasource.url=jdbc:postgresql://localhost:5432/todoist
spring.datasource.username=david_an
spring.datasource.password=
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create-drop